### PR TITLE
More commands!

### PR DESCRIPTION
**Pull request by AL1L**

### CODE REVIEW

**Comment by NahuLD** [comment]
Let's make this a thing

**Comment by deprilula28** [comment]
a

**Comment by AL1L** [comment]
a

**Comment by NahuLD** [comment]
Let's keep the good work coming

**Review by Proximyst — CHANGES_REQUESTED** [review]
YesNo will not be a thing and thus should be removed before merge. Http can happily go with it, or simply stay.

**Review by Proximyst — APPROVED** [review]

**Pull request merged**
